version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    command: -p 6500
    expose:
      - 6500
    env_file:
      - ./.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: [ "CMD", "pg_isready", "-h", "localhost", "-p", "6500", "-U", "${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: currency_exchange_api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    ports:
      - 8001:8000
    depends_on:
      - postgres
    command: [ '/currency_exchange_api/docker/app.sh' ]

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'
    restart: always
