version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - "${DB_PORT}:5432"
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'
    restart: always
    volumes:
      - redis-data:/data

volumes:
  postgres-db:
  redis-data: