"""Added image_path to User

Revision ID: 92a68bcb8740
Revises: 13873a89cbd9
Create Date: 2024-03-15 22:30:20.532602

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "92a68bcb8740"
down_revision: Union[str, None] = "13873a89cbd9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "balances",
        "amount",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=10, scale=2),
        existing_nullable=False,
        existing_server_default=sa.text("'0'::double precision"),
    )
    op.add_column("users", sa.Column("image_path", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "image_path")
    op.alter_column(
        "balances",
        "amount",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
        existing_server_default=sa.text("'0'::double precision"),
    )
    # ### end Alembic commands ###
