"""added field is_admin

Revision ID: d87b082dab96
Revises: 6ae7b347fc8b
Create Date: 2024-02-28 21:17:08.329610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d87b082dab96"
down_revision: Union[str, None] = "6ae7b347fc8b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("is_admin", sa.Boolean(), server_default="False", nullable=False),
    )
    op.alter_column(
        "users",
        "balance",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_nullable=False,
        existing_server_default="0",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "balance",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        existing_server_default="0",
    )
    op.drop_column("users", "is_admin")
    # ### end Alembic commands ###
